FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Faustin
# Bloc with hover
 [
    {
        bloc : [
            {
                titre : "lalclaelzrlz"
            },
            {titre : "lalclaelzrlz"},
            {titre : "lalclaelzrlz"},
        ]  
    }
  ]