FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Faustin

 [
      {
          "image a droite": "Kyoterra-logo-300x95",
          "elements": "kyoterra", "pourquoi une fondation", "services", "references", "contact",
          "choices": [
              {
                  "choice": "Swift2",
                  "votes": 2048
              }, {
                  "choice": "Python",
                  "votes": 1024
              }, {
                  "choice": "Objective-C",
                  "votes": 512
              }, {
                  "choice": "Ruby",
                  "votes": 256
              }
          ]
      }
  ]